In [1]:
# Dependencies and setup
%matplotlib inline
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
projections = pd.read_csv('../data/rawdata/reservoirs_and_bayou.csv')
projections.head()

,year,FIPS,County,Total,Male total,Female total,Caucasian total,Caucasian male,Caucasian Female,African American total,...,African American Female,Latino Total,Latino Male,Latino Female,Asian Total,Asian Male,Asian Female,Other Total,Other Male,Other Female
0,2010,39,Brazoria County,313166,159000,154166,166674,83696,82978,36880,...,17502,86643,44846,41797,17013,8181,8832,5956,2899,3057
1,2011,39,Brazoria County,319061,161896,157165,167347,83993,83354,38220,...,18196,89537,46295,43242,17798,8580,9218,6159,3004,3155
2,2012,39,Brazoria County,325102,164870,160232,167970,84266,83704,39617,...,18927,92525,47796,44729,18600,8994,9606,6390,3124,3266
3,2013,39,Brazoria County,331162,167836,163326,168531,84499,84032,41055,...,19678,95561,49328,46233,19416,9405,10011,6599,3227,3372
4,2014,39,Brazoria County,337296,170856,166440,169017,84701,84316,42529,...,20450,98668,50898,47770,20258,9836,10422,6824,3342,3482